### ISSUE TITLE
Basic Errors on Stop-Estimating-Start-Navigating

### ISSUE THREAD

**Issue by ambition-consulting** [risk-first/website#46]
![image](https://user-images.githubusercontent.com/4218334/106677744-951d1b80-65b9-11eb-9074-0114df89e3e3.png)

**Comment by ambition-consulting** [comment]
Ah, I guess I should have read the "under construction" label more carefully. maybe you should put a small icon on the menu also to highlight this article not really being finished?

**Comment by ambition-consulting** [comment]
I discovered your web site yesterday and find it really well thought - made me order your book in fact.

@robmoffat: Could you do me a favour and answer one unrelated question though?

I assume the testing framework you have written about spending some time on and then giving up was the pure4j library - how come you have archived it? Isn't the identification and extraction of pure functions (and all the other goodies this library allows) a great asset in making software more predictable for pure functions, and reduce the risk of failure by lowering the amount of dangerous code, that needs to be careful looked at after extraction?

**Comment by robmoffat** [comment]
Hi John-Paul,

I’m not sure which page you’re talking about here, but it is probably Pure4J, even though that’s not exactly a testing framework.  Pure4J came about as I was working on building lots of end-to-end tests for other people’s code. I also wrote an extension for Concordion at this time to allow you to use Excel spreadsheets for defining tests.  

This testing was really hard work and because of the lack of purity of any of that code, often it was hard to get things deterministic.  The code under test would call off to databases, environment variables, other services, etc.  and so the boundary of the tests kept increasing.

What you say is right - using pure functions totally alleviates that problem and is a massive boon for predictability.   And, Pure4J actually worked:  it did a really good job of determining when you’d written pure functional code, and when you hadn’t.  The only problem was, fixing your code to be pure-functional was both a pain and led to some quite non-idiomatic Java at the end of it. So, I couldn’t see it getting wide adoption and I think would cause more frustration than anything else.

What I might have done, had I wanted to persist with it, was to pull out the persistent collections framework (taken from Clojure and made more Java-ery) and present that as a library in it’s own right.  That could have been quite useful.

I think now that purity isn’t really a problem you can solve in Java with a library.  You have to go wider.  Languages like Clojure and Kotlin, while they don't enforce purity, they do encourage it in the features they provide, and this is probably an easier way in for Java developers.

Glad you’re enjoying Risk-First though!
