### ISSUE TITLE
How many of you write programs every working day?

### ISSUE THREAD

**Issue by r-pankevicius** [risk-first/website#58]
So you know the subject you're talking about. Or trying to teach others how to do good estimations, write decent programs and stuff like that.

**Comment by robmoffat** [comment]
Good question!  I feel like I do code nearly every working day, though not so much at the weekend.  My git summary seems to show the same

![Screenshot 2023-03-16 at 08 23 29](https://user-images.githubusercontent.com/568673/225557584-363e5ed6-e061-4d4f-8b7f-9b4656bbc7d4.png)

Personally, I worry that if I stopped, I would lose the ability... so it's a skill I am constantly practicing.  I also avoid jobs where this skill would atrophy, since I think I would need it again in the future.

Would be interested to hear from everyone else on this?

**Comment by r-pankevicius** [comment]
Just wanted to check how much close to the code people promoting "risk first" is. No bullying intended, just a small bite.

**Comment by javajenks** [comment]
I go through bursts of productivity depending on what particular project im working on. Some projects require coding, others do not - although i agree with @robmoffat - for me its something that i will always do because i enjoy it !

**Comment by r-pankevicius** [comment]
I started with "Agile is Dead" ([example](https://www.youtube.com/watch?v=a-BOSpxYJ9M&t=1297s) from Dave Thomas), looking for ways to "reclaim agility". First I bumped on post-agile term. What I found there it's most likely the continuation of "long dead agile". Then I found risk-first. The question if it's attempt is to revive agile or create a new arena for consulting business?
